/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import cpo_mastermind_durac_degennaro.CelluleGraphique;
import cpo_mastermind_durac_degennaro.Combinaison;
import cpo_mastermind_durac_degennaro.Pion;
import cpo_mastermind_durac_degennaro.PlateauDeJeu;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author flavi
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    private ArrayList<Character> couleursDisponibles;
    private PlateauDeJeu grille;
    private Combinaison combinaisonSecrete;
    private int nbCoups;
   
      
    public FenetrePrincipale() {
        initComponents();
        int nbLignes= 12;
        int nbColonnes = 4;
        
        Font font = new Font("Arial", Font.PLAIN, 30); // Police Arial, normale, taille 20
        jLabel3.setFont(font);
        
        
        this.couleursDisponibles = new ArrayList<>();
        this.couleursDisponibles.add('R'); 
        this.couleursDisponibles.add('B'); 
        this.couleursDisponibles.add('J'); 
        this.couleursDisponibles.add('V'); 
        this.couleursDisponibles.add('W'); 
        this.couleursDisponibles.add('O');
      
      //on initialise la grille et la combinaison secrète
        this.grille = new PlateauDeJeu(nbLignes, nbColonnes);
        this.combinaisonSecrete = Combinaison.genererAleatoire(4, this.couleursDisponibles);
        
        System.out.println(combinaisonSecrete);
        PanneauGrille.setLayout(new GridLayout (nbLignes, nbColonnes));
        //jPanel1.setLayout(new GridLayout (nbLignes, nbColonnes));
        
        // on met les cellules dans le tableau, cf tuto
        for (int i=0; i< nbLignes; i++){
            for (int j=0; j<nbColonnes; j++){
                //JButton bouton_cellule = new JButton ();
                CelluleGraphique bouton_cellule = new CelluleGraphique( grille.obtenirGrille(), i,j); //matricecellules à remplacer avec la grille qu'on aura créé
                PanneauGrille.add(bouton_cellule);
            }
        }
        
        
        jPanel1.setLayout(new GridLayout(12, 2, 5, 5)); // 12 lignes, 2 colonnes, espace de 5px entre les cellules

        for (int i = 0; i < 12; i++) {
            // Première colonne : "Bien placés :"
            JLabel labelBienPlaces = new JLabel("Bien placés :", SwingConstants.CENTER);
            labelBienPlaces.setBorder(BorderFactory.createLineBorder(Color.BLACK)); // Ajout d'une bordure
            jPanel1.add(labelBienPlaces); // Ajouter au panel

    // Deuxième colonne : "Bonne couleur :"
            JLabel labelBonneCouleur = new JLabel("Mal placés :", SwingConstants.CENTER);
            labelBonneCouleur.setBorder(BorderFactory.createLineBorder(Color.BLACK)); // Ajout d'une bordure
            jPanel1.add(labelBonneCouleur); // Ajouter au panel
}
        
    }
    
    
    private Color getColorFromChar(char couleur) {
    switch (couleur) {
        case 'R': return Color.RED;    
        case 'B': return Color.BLUE;   
        case 'J': return Color.YELLOW; 
        case 'V': return Color.GREEN;  
        case 'W': return Color.WHITE;
        case 'O': return Color.ORANGE; 
        default: return Color.GRAY;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 650));

        PanneauGrille.setBackground(new java.awt.Color(0, 0, 255));
        PanneauGrille.setPreferredSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("MASTERMIND");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new java.awt.GridLayout(12, 2, 3, 5));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 4));

        jButton1.setText("Couleurs 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Couleurs 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("Couleurs 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setText("Couleurs 4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        jButton5.setText("Valider");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanneauGrille, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(206, 206, 206))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanneauGrille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    changeCouleur(nbCoups, 0);  // modifie dans la premiere colonne 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    changeCouleur(nbCoups, 1);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    changeCouleur(nbCoups, 2);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    changeCouleur(nbCoups, 3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    validerCombinaison();
    
        
    }//GEN-LAST:event_jButton5ActionPerformed

    
    
 // on change la couleur d'une case
private void changeCouleur(int ligne, int colonne) {
    char[] couleurs = {'R', 'B', 'J', 'V', 'W', 'O'};
    Pion pionActuel = grille.obtenirGrille()[ligne][colonne];
    
    // Si la case est vide, on met la couleur rouge par défaut
    if (pionActuel == null) {
        grille.obtenirGrille()[ligne][colonne] = new Pion(couleurs[0]);
    } else {
        // Trouve la couleur suivante dans la liste
        int indexCouleur = indice(couleurs, pionActuel.getCouleur());
        int nextIndex = (indexCouleur + 1) % couleurs.length;
        grille.obtenirGrille()[ligne][colonne] = new Pion(couleurs[nextIndex]);
    }
    
    // Mise à jour de la couleur dans l'interface
    PanneauGrille.getComponent(ligne * grille.getNbColonnes() + colonne)
        .setBackground(getColorFromChar(grille.obtenirGrille()[ligne][colonne].getCouleur()));

    PanneauGrille.repaint();
}

// indice de la couleur dans le tableau
private int indice(char[] couleurs, char couleur) {
    for (int i = 0; i < couleurs.length; i++) {
        if (couleurs[i] == couleur) {
            return i;
        }
    }
    return -1; //peut etre qu'on peut mettre autre chose ?
}

private void validerCombinaison() {
    //on crée une combinaison à partir des pions choisis
    Pion[] combinaisonTentative = new Pion[grille.getNbColonnes()];
    for (int i = 0; i < grille.getNbColonnes(); i++) {
        combinaisonTentative[i] = grille.obtenirGrille()[nbCoups][i];
    }

    Combinaison tentative = new Combinaison(combinaisonTentative);
    
    //on compare avec la combinaison secrète, comparer() est dans Combinaison
    int[] indices = combinaisonSecrete.comparer(tentative);
    
    
    //System.out.println("Combinaison secrète : " + combinaisonSecrete);
    //System.out.println("Tentative : " + tentative);
    //System.out.println("Comparaison : " + combinaisonSecrete.equals(tentative));
    //System.out.println("Nombre de coups joués : " + nbCoups);

    //pour la victoire
    if (indices[0] == 4) {
        
        this.dispose(); // on ferme la fenêtre de jeu

        // on crée une nouvelle fenêtre pour le message
        JFrame victoireFenetre = new JFrame("Victoire");
        JOptionPane.showMessageDialog(victoireFenetre, "Vous avez gagné !");
        victoireFenetre.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        System.exit(0);
        return;
    }
    
    // on a créé des labels pour afficher les pions placés
    //jLabel1.setText("Bien placés : " + indices[0]);
    //jLabel2.setText("Mal placés : " + indices[1]);
    
    //pour la défaite
    if (nbCoups==11){
        this.dispose();
        JFrame defaiteFenetre = new JFrame("Defaite");
        JOptionPane.showMessageDialog(defaiteFenetre, "Vous avez perdu...");
        defaiteFenetre.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        System.exit(0);
        return;
        
    }
    nbCoups++;   
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
